parameters:
    time.now: 'local' # local or world
    toggles:
        invert_time_machine: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            array $toggles: '%toggles%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # Storage

    App\Clock\Storage\ClockStorageInterface: '@App\Clock\Storage\CacheClockStorage'

    # Time Factory

    App\Clock\Time\TimeFactoryInterface: '@App\Clock\Time\TimeFactory'

    App\Clock\Time\TimeFactory:
        autoconfigure: false
        arguments:
            - !tagged_iterator 'time.factory'

    App\Clock\Time\TimeInterface:
        factory: ['@App\Clock\Time\TimeFactoryInterface', 'create']
        arguments:
            - '%time.now%'

    # Strategies

    App\Clock\Strategy\MoveTimeHandlerInterface:
        factory: '@App\Clock\Strategy\MoveTimeHandlerFactory'

    App\Clock\Strategy\MoveTimeHandlerInterface $advanceTimeHandler: '@App\Clock\Strategy\AdvanceTimeHandler'
    App\Clock\Strategy\MoveTimeHandlerInterface $goBackTimeHandler: '@App\Clock\Strategy\GoBackTimeHandler'
    App\Clock\Strategy\MoveTimeHandlerInterface $nullTimeHandler: '@App\Clock\Strategy\NullTimeHandler'

when@prod:
    parameters:
        time.now: 'world'

    services:
        App\Clock\Storage\ClockStorageInterface: '@App\Clock\Storage\NullClockStorage'

