parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $env: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
