parameters:
    toggles:
        invert_time_machine: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            array $toggles: '%toggles%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Clock\Storage\ClockStorageInterface: '@App\Clock\Storage\CacheClockStorage'

when@prod:
    services:
        App\Clock\Storage\ClockStorageInterface: '@App\Clock\Storage\NullClockStorage'
