parameters:
    toggles:
        invert_time_machine: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $env: '%kernel.environment%'
            array $toggles: '%toggles%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
